### ISSUE TITLE
Version 1.0.3 crashed Node-red

### ISSUE THREAD

**Issue by DanielsNoJack** [damoclark/node-red-contrib-gpsd#6]
node-red-contrib-gpsd: 1.0.3
Node-red: 1.2.9
Node.js: 12.22.1
o.s. Debian 10

```
[info] [gpsd:b2bd8a2c.4e8cf] Connected to gpsd
[red] Uncaught Exception:
ReferenceError: listener is not defined
at /home/spravce/.nodered-chcell/node_modules/node-red-contrib-gpsd/gpsd/gpsd.js:188:4
at Socket.<anonymous> (/home/spravce/.nodered-chcell/node_modules/node-gpsd/lib/gpsd.js:125:11)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:326:22)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1130:10)
Main process exited, code=exited, status=1/FAILURE
```

**Comment by damoclark** [comment]
Thanks for reporting this bug.  I've just uploaded a fix with version 1.0.4.
